# Generated by Django 5.1.3 on 2024-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_email_alter_review_comment_otptoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='tp_created_at',
            new_name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8a883a', max_length=6),
        ),
    ]
