# Generated by Django 5.1.3 on 2024-12-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_otptoken_otp_code_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='value',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='52f720', max_length=6),
        ),
        migrations.AddField(
            model_name='variant',
            name='colour',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.colour'),
        ),
        migrations.AddField(
            model_name='variant',
            name='storage',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storage'),
        ),
    ]
