# Generated by Django 5.1.3 on 2024-12-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_otptoken_otp_code_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c40e73', max_length=6),
        ),
    ]
