# Generated by Django 5.1.3 on 2024-12-19 10:25

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_created_at_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='uploads/product/lap.jpg', force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[300, 250], upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='bf9332', max_length=6),
        ),
        migrations.CreateModel(
            name='VaraintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[300, 250], upload_to='uploads/product_images/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='store.variant')),
            ],
        ),
    ]
