# Generated by Django 5.1.3 on 2024-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_variant_thumbnail_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VaraintImage',
            new_name='VariantImage',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='729d83', max_length=6),
        ),
    ]
