# Generated by Django 5.1.3 on 2024-12-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_varaintimage_variantimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0e5bb1', max_length=6),
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
