# Generated by Django 5.1.3 on 2024-12-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_otptoken_otp_code_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant_images',
            name='variant_colour',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='51318c', max_length=6),
        ),
        migrations.DeleteModel(
            name='Variant_Colour',
        ),
        migrations.DeleteModel(
            name='Variant_Images',
        ),
    ]
