# Generated by Django 5.1.3 on 2025-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_variant_images_variant_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1b3d4a', max_length=6),
        ),
    ]
