# Generated by Django 5.1.3 on 2025-01-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order_razorpay_payment_id_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e99783', max_length=6),
        ),
    ]
