# Generated by Django 5.1.3 on 2025-01-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_order_status_alter_otptoken_otp_code'),
        ('store', '0034_alter_otptoken_otp_code'),
    ]

    operations = [
    ]
