# Generated by Django 5.1.3 on 2025-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_merge_20250106_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='641efc', max_length=6),
        ),
    ]
