# Generated by Django 5.1.3 on 2025-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_orderitem_return_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='reason',
            field=models.TextField(default='No reason provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='962eba', max_length=6),
        ),
    ]
