# Generated by Django 5.1.3 on 2025-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_returnrequest_is_refunded_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='9eaa50', max_length=6),
        ),
    ]
