# Generated by Django 5.1.3 on 2025-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_brand_alter_otptoken_otp_code_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c4905b', max_length=6),
        ),
    ]
