# Generated by Django 5.1.3 on 2025-01-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_remove_wishlist_product_wishlist_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6088d4', max_length=6),
        ),
    ]
