# Generated by Django 5.1.3 on 2025-01-19 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_typecategory_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d62ca3', max_length=6),
        ),
    ]
