# Generated by Django 5.1.3 on 2025-01-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_offer_end_date_alter_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='60459e', max_length=6),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='store.variant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product', 'variant')},
        ),
    ]
