# Generated by Django 5.1.3 on 2025-02-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_wishlist_product_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8a8750', max_length=6),
        ),
    ]
